# yaml-language-server: $schema=../../schema.json
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: angular-build-deploy-suva
  labels:
    app.kubernetes.io/version: "1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.35.0"
    tekton.dev/tags: angular, sonar, buildah, skopeo, deploy, openpr, notify
    tekton.dev/displayName: angular-build-deploy-suva
    pipelinesascode.tekton.dev/task-1: "suva://git-clone-suva:1.0"
    pipelinesascode.tekton.dev/task-2: "suva://sonarqube-scanner-suva:1.0"
    pipelinesascode.tekton.dev/task-3: "suva://parse-release-tag-suva:1.0"
    pipelinesascode.tekton.dev/task-4: "suva://buildah-build-suva:1.0"
    pipelinesascode.tekton.dev/task-6: "suva://skopeo-push-suva:1.0"
    pipelinesascode.tekton.dev/task-7: "suva://git-patch-lowest-stage-image-suva:1.0"
    pipelinesascode.tekton.dev/task-8: "suva://git-open-pr-kustomize-suva:1.0"
    pipelinesascode.tekton.dev/task-9: "suva://teams-notification-suva:1.0"
    pipelinesascode.tekton.dev/task-10: "suva://pvc-cleanup-suva:1.0"
spec:
  description: >-
    This pipeline runs sonar scans on the source code
    and pushes the built image to the registry. It also patches the lowest stage
    of the application, opens a PR for the other stages, and sends notifications to the teams.
  params:
    # global params
    - name: git-url
      description: The git ssh url.
    - name: git-revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...).
    - name: target-image
      description: The target image to push
    - name: git-url-infra
      description: The git ssh url of the infra-project.
    ## optional
    - name: git-revision-infra
      description: The git revision of the infra-project.
      default: "master"
    - description: Log the commands that are executed in verbose mode.
      name: verbose
      type: string
      default: "true"

    # sonarqube-scanner-suva
    - name: sonar-project-key
      description: The sonar project key
    ## optional
    - name: sonar-source-to-scan
      description: The source to scan by sonar. Typically the root of the project or 'src'.
      default: "."
    - name: sonar-scanner-opts
      description: The options to be passed to the sonar-scanner command
      default: "-Xmx2048m"
    - name: sonar-angular-coverage-path
      description: The path to the coverage report for angular
      default: "coverage.xml"

    # buildah-build-suva
    ## optional
    - name: storage-driver
      description: Set buildah storage driver
      default: "vfs"
    - name: build-extra-args
      description: Extra parameters passed for the build command when building images.
      default: ""

    # git-patch-lowest-stage-image-suva
    - name: kustomize-lowest-stage
      description: The lowest stage of the application (typically entw).
    ## optional
    - default: "tekton@suva.ch"
      description: |
        Git user email for performing git operation.
      name: git-user-mail
      type: string
    - default: "tekton"
      description: |
        Git user name for performing git operation.
      name: git-user-name
      type: string

    # git-open-pr-kustomize-suva
    ## optional
    - name: stages
      description: |
        The name of the stages to open pr. Example "[entw,intg,prod]"
      type: string
      default: "[]"
    - name: stage-type
      description: |
        Wether the stages are folders or branches folder|branch
      type: string
      default: "folder"
    - name: bitbucket-credential-secret-name
      description: Name of the Secret containing the Bitbucket credentials.
      type: string
      default: "bitbucket-access-key-credential"
    - name: loglevel
      description: Set the loglevel
      type: string
      default: "info"
    - name: cleanup-old-pr
      description: Wether to cleanup old prs & branches
      type: string
      default: "true"
    - name: set-assignee
      description: Wether to set the assignee
      type: string
      default: "false"
    - name: open-pr-git-user-name
      description: The git user name
      type: string
      default: "tekton-auto-pr"
    - name: open-pr-git-user-mail
      description: The git user email
      type: string
      default: "tekton-auto-pr@suva.ch"

    # pvc-cleanup-suva
    ## optional
    - name: max-pipelines
      description: Keep only x number of pipelines
      type: string
      default: "50"
    - name: retention-days
      description: Delete pipelines older than x days
      type: string
      default: "3"

    # teams-notification-suva
    - name: commit-id
      description: Commit-id delivered by bitbucket/git.
      type: string
    - name: repo-name
      type: string
      description: Name of bitbucket/git repo.
    - name: actor-name
      type: string
      description: Name of the actor, who triggered the build.
    - name: repo-browser-link
      type: string
      description: Bitbucket base url.
    ## optional
    - name: cluster
      description: The cluster on which the pipelie will run.
      default: "osp"
    - name: webhook-url-secret
      type: string
      default: teams-webhook-url
      description: Name of the secret with incoming webhook URL
    - name: webhook-url-secret-key
      type: string
      default: url
      description: Key in the secret
    - name: duration-log-level
      description: Decide between "none", "basic" and "extended" Level of Information of the Information about the Build Duration of the Task
      default: "basic"
      type: string
    - name: notify-when-pipeline-status-is
      type: array
      description: The notification will sent only if the pipeline status is in this list.
      default: ["Failed", "None"]
  workspaces:
    - name: source-app
      description: The workspace containing the source of the Git App-Repo to build.
    - name: source-infra
      description: The workspace containing the source of the Git Infra-Repo to build.
    - name: image
      description: The workspace containing the built image.
    - name: ca-directory
      description: The workspace containing the trusted ca-bundle. Needed by the teams-notification-suva
    - name: ssh-directory
      description: A .ssh directory with private key, known_hosts, config, etc. Copied to the user's home before git commands are executed. Used to authenticate with the git remote when performing the clone. Binding a Secret to this Workspace is strongly recommended over other volume types.
  tasks:
    - name: git-clone-suva
      taskRef:
        name: git-clone-suva
        kind: Task
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: source-app
    - name: sonarqube-scanner-suva
      runAfter:
        - git-clone-suva
      taskRef:
        name: sonarqube-scanner-suva
        kind: Task
      params:
        - name: git-revision
          value: $(params.git-revision)
        - name: sonar-project-key
          value: $(params.sonar-project-key)
        - name: source-to-scan
          value: $(params.sonar-source-to-scan)
        - name: sonar-scanner-opts
          value: $(params.sonar-scanner-opts)
        - name: sonar-angular-coverage-path
          value: $(params.sonar-angular-coverage-path)
      workspaces:
        - name: source
          workspace: source-app
    - name: parse-release-tag-suva
      runAfter:
        - git-clone-suva
      taskRef:
        name: parse-release-tag-suva
        kind: Task
      params:
        - name: git-revision
          value: $(params.git-revision)
    - name: buildah-build-suva
      runAfter:
        - parse-release-tag-suva
      taskRef:
        kind: Task
        name: buildah-build-suva
      params:
        - name: image
          value: $(params.target-image):$(tasks.parse-release-tag-suva.results.release-tag)
        - name: storage-driver
          value: $(params.storage-driver)
        - name: build-extra-args
          value: $(params.build-extra-args)
      workspaces:
        - name: source
          workspace: source-app
        - name: image
          workspace: image
    - name: skopeo-push-suva
      runAfter:
        - buildah-build-suva
      taskRef:
        kind: Task
        name: skopeo-push-suva
      params:
        - name: image
          value: $(params.target-image):$(tasks.parse-release-tag-suva.results.release-tag)
      workspaces:
        - name: image
          workspace: image
    - name: git-clone-suva-infra
      taskRef:
        name: git-clone-suva
        kind: Task
      params:
        - name: url
          value: $(params.git-url-infra)
        - name: revision
          value: $(params.git-revision-infra)
      workspaces:
        - name: source
          workspace: source-infra
    - name: git-patch-lowest-stage-image-suva
      runAfter:
        - git-clone-suva-infra
        - skopeo-push-suva
      taskRef:
        name: git-patch-lowest-stage-image-suva
        kind: Task
      params:
        - name: revision
          value: $(tasks.parse-release-tag-suva.results.release-tag)
        - name: target-image
          value: $(params.target-image)
        - name: kustomize-lowest-stage
          value: $(params.kustomize-lowest-stage)
        - name: revision-infra
          value: $(params.git-revision-infra)
        - name: git-user-name
          value: $(params.git-user-name)
        - name: git-user-mail
          value: $(params.git-user-mail)
        - name: verbose
          value: $(params.verbose)
      workspaces:
        - name: source
          workspace: source-infra
        - name: ssh-directory
          workspace: ssh-directory
    - name: git-open-pr-kustomize-suva
      when:
        - input: $(params.stages)
          operator: notin
          values: ["", "[]"]
      runAfter:
        - git-patch-lowest-stage-image-suva
      taskRef:
        name: git-open-pr-kustomize-suva
        kind: Task
      params:
        - name: stages
          value: $(params.stages)
        - name: target-image
          value: $(params.target-image)
        - name: bitbucket-credential-secret-name
          value: $(params.bitbucket-credential-secret-name)
        - name: revision
          value: $(tasks.parse-release-tag-suva.results.release-tag)
        - name: git-url-infra
          value: $(params.git-url-infra)
        - name: stage-type
          value: $(params.stage-type)
        - name: loglevel
          value: $(params.loglevel)
        - name: infra-revision
          value: $(params.git-revision-infra)
        - name: cleanup-old-pr
          value: $(params.cleanup-old-pr)
        - name: set-assignee
          value: $(params.set-assignee)
        - name: assignee
          value: $(params.actor-name)
        - name: git-user-name
          value: $(params.open-pr-git-user-name)
        - name: git-user-email
          value: $(params.open-pr-git-user-mail)
      workspaces:
        - name: source
          workspace: source-infra
        - name: ssh-directory
          workspace: ssh-directory
    - name: pvc-cleanup-suva
      taskRef:
        name: pvc-cleanup-suva
        kind: Task
      params:
        - name: max-pipelines
          value: $(params.max-pipelines)
        - name: retention-days
          value: $(params.retention-days)
  finally:
    - name: teams-notification-suva
      when:
        - input: $(tasks.status)
          operator: notin
          values: ["", "[]"]
        - input: $(tasks.status)
          operator: in
          values: ["$(params.notify-when-pipeline-status-is[*])"]
      params:
        - name: cluster
          value: $(params.cluster)
        - name: webhook-url-secret
          value: $(params.webhook-url-secret)
        - name: webhook-url-secret-key
          value: $(params.webhook-url-secret-key)
        - name: commit-id
          value: $(params.commit-id)
        - name: repo-name
          value: $(params.repo-name)
        - name: actor-name
          value: $(params.actor-name)
        - name: repo-browser-link
          value: $(params.repo-browser-link)
        - name: target-image
          value: $(params.target-image)
        - name: git-revision
          value: $(params.git-revision)
        - name: namespace
          value: $(context.pipelineRun.namespace)
        - name: pipeline
          value: $(context.pipelineRun.name)
        - name: tasks-status
          value: $(tasks.status)
        - name: duration-log-level
          value: $(params.duration-log-level)
      taskRef:
        kind: Task
        name: teams-notification-suva
      workspaces:
        - name: source
          workspace: source-app
        - name: ca-directory
          workspace: ca-directory
