apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: "syr-kpm-ng-frontend-{{sender}}-"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
    pipelinesascode.tekton.dev/pipeline: "suva://git-tag-release-suva:1.0"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  pipelineRef:
    name: git-tag-release-suva
  serviceAccountName: pipeline
  podTemplate:
    nodeSelector:
      node-role.kubernetes.io/appinfra: ""
    tolerations:
      - key: appinfra
        effect: NoExecute
        value: reserved
  params:
    - name: git-revision
      value: "{{target_branch}}"
    - name: git-url
      value: "ssh://git@git.suvanet.ch/scsyrius/syr-kpm-ng-frontend.git"
    - name: commit-id
      value: "{{revision}}"
    - name: repo-name
      value: "{{repo_name}}"
    - name: actor-name
      value: "{{sender}}"
    - name: repo-browser-link
      value: "{{repo_url}}"
    - name: create-release-candidate
      value: "false"

  workspaces:
    - name: source-app
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
          storageClassName: hnas-nfs-csi-sc
    - name: ssh-directory
      secret:
        secretName: bitbucket-key
    - name: ca-directory
      configMap:
        name: suva-ca
